version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - '5432:5432'
  graphql-engine:
    image: hasura/graphql-engine:v1.3.0
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: supersecret
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDCTCCAfGgAwIBAgIJYJcXo7LAraA3MA0GCSqGSIb3DQEBCwUAMCIxIDAeBgNV\nBAMTF3RvbS1zY2hhbGwuZXUuYXV0aDAuY29tMB4XDTIwMDgyOTE1MjMxOVoXDTM0\nMDUwODE1MjMxOVowIjEgMB4GA1UEAxMXdG9tLXNjaGFsbC5ldS5hdXRoMC5jb20w\nggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC0i77j8/h9qGvqCfzYw4fL\nYA4isxle4H/ntAJNQefoTIGExA1Nw2ECyjUljuH2SO2sTXhwOebqEBxqaD5gv9S4\nfgToZms90DSpNm877ybMXtJyUd4hTDgvI8OCSkmiGSzKXD38ctOJceJIyDv4cl5C\nzS9rxwiJ1UaLaz77WjVQTTpZ0otHcKcE8JnXmSM0TLSHZ6eUK0pakqAmMmLhzQUa\nx/NhwyCZJYZjWbAFJ2eq7T8eqD9Rsfu4gImm4yJj9ie+40V3GxdWuQ0jiqTdS4Xu\n2FMOfs+tP7592L0r7og/4d4KogS2NHI1bJ7WqbbyjnDUBDRsuTx8HAS589JZrjfF\nAgMBAAGjQjBAMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFHhU75Uaw5k+rbqx\nT9ouhQrZ1SyNMA4GA1UdDwEB/wQEAwIChDANBgkqhkiG9w0BAQsFAAOCAQEAZtHO\n29D5ryJyoqCB56U9RHuHg6B2Jf3BK3kQqx/+yDHXi6xY0WjpFwv4saB/esogmX0Y\nM1AMD9AoTx0Dvk74B60n3LR1/ODRPgs1CAyie/hIeEq66ScqFb741MVitWgfrpRK\n9vJSjJykfpy+p1X2noIOlcpyjLvAFvRxQF8XgR2qpXlyH1mVKmS2j1xGt8lqJUXX\nJzn+tODFMK1DW+LBxRoZ5eWiB2ebf3KJUICgtqH0HRG/x43b3glfNRPURVbYyNOz\nw8BKHD7fp9wd52sGtzNw8+eWN9It5X7bZhSDJ3sjqoF0+gpyXdn7t1JJcSMQJxl8\nopIihi3H7M7cUM6fXw==\n-----END CERTIFICATE-----"}'

volumes:
  db_data:
